# limitations under the License.
#

# spring.main.web-application-type=none

# NOTE: You must disable the banner and the console logging
# to allow the STDIO transport to work !!!
# Config reference: https://docs.spring.io/spring-ai/reference/api/mcp/mcp-server-boot-starter-docs.html#_webflux_server_configuration
# Spring Boot 应用配置
spring:
  # Spring Boot 主配置
  main:
    # 关闭启动时的 Spring Boot 横幅（banner）
    banner-mode: off

  # AI 相关配置
  ai:
    # MCP (Model Control Protocol) 服务器配置
    mcp:
      server:
        # MCP 服务器实例名称
        name: test-tool-mcp-server

        # MCP 服务器版本号
        version: 0.0.1

        # 服务器类型 - ASYNC 推荐用于响应式/非阻塞应用
        type: sync  # 这里配置的同步模式

        # SSE (服务器发送事件) 配置:
        # SSE 基础路径 - 默认值为 /sse
        # 最终访问路径为: {基础URL}/sse/mcp
        sse-endpoint: /sse

        # 消息端点，将附加到 SSE 基础路径后
        sse-message-endpoint: /mcp

        # 服务器功能配置:
        # 启用/禁用各种 MCP 服务器功能
        capabilities:
          tool: true       # 启用工具功能
          resource: true   # 启用资源处理功能
          prompt: true     # 启用提示功能
          completion: true # 启用补全功能


server:
  port: 9002
# logging.pattern.console=