spring:
  main:
    web-application-type: none  # 禁用 Spring Boot 的 Web 应用程序
    banner-mode: off  # 禁用 Spring Boot 的 Banner
  ai:
    mcp:
      server:
        name: test-tool-mcp-server  # MCP 服务器名称
        version: 0.0.1                      # MCP 服务器版本
        stdio: true                        # 是否启用 STDIO 传输

# NOTE: You must disable the banner and the console logging
# to allow the STDIO transport to work !!!

logging:
  level:
    root: off
    org.springframework: off
